dependencies:
  - smartcontractkit/chainlink@1.1.0
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@3.4.2
dotenv: .env
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.0"
      - "@chainlink-brownie=smartcontractkit/chainlink-brownie-contracts@0.3.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.2"
networks:
  default: development
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  rinkeby:
    vrfcoordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
    explorer_api: "https://api-rinkeby.etherscan.io/api"
wallets:
  MM1: ${MM1_PRIVATE_KEY}
  MM2: ${MM2_PRIVATE_KEY}
api_keys:
  etherscan: ${ETHERSCAN_TOKEN}
